### ISSUE TITLE
Does the unitree_api package exist?

### ISSUE THREAD

**Issue by kkjing4444** [abizovnuralem/go2_ros2_sdk#101]
Dear author, I'm sorry to bother you again, and thank you very much for your help before. When I ran it, it showed that I could not find the unitree_api package, I would like to ask the author if you have this package on GitHub?

**Comment by abizovnuralem** [comment]
Hello! Can you please send me a full log of the error?

**Comment by abizovnuralem** [comment]
How did you clone the repo? Have you done git clone --recurse-submodules https://github.com/abizovnuralem/go2_ros2_sdk.git src ?

**Comment by kkjing0414** [comment]
[INFO] [launch]: All log files can be found below /home/unitree/.ros/log/2024-10-30-19-39-29-512138-ubuntu-4921
[INFO] [launch]: Default logging verbosity is set to INFO
IP list: ['192.168.55.112']
[INFO] [robot_state_publisher-1]: process started with pid [4922]
[INFO] [pointcloud_to_laserscan_node-2]: process started with pid [4924]
[INFO] [go2_driver_node-3]: process started with pid [4926]
[INFO] [lidar_to_pointcloud-4]: process started with pid [4928]
[INFO] [rviz2-5]: process started with pid [4930]
[INFO] [joy_node-6]: process started with pid [4932]
[INFO] [teleop_node-7]: process started with pid [4934]
[INFO] [twist_mux-8]: process started with pid [4938]
[INFO] [foxglove_bridge-9]: process started with pid [4972]
[INFO] [async_slam_toolbox_node-10]: process started with pid [4976]
[INFO] [controller_server-11]: process started with pid [4987]
[INFO] [smoother_server-12]: process started with pid [4997]
[INFO] [planner_server-13]: process started with pid [5002]
[INFO] [behavior_server-14]: process started with pid [5016]
[INFO] [bt_navigator-15]: process started with pid [5031]
[INFO] [waypoint_follower-16]: process started with pid [5033]
[INFO] [velocity_smoother-17]: process started with pid [5043]
[INFO] [lifecycle_manager-18]: process started with pid [5051]
[robot_state_publisher-1] [INFO] [1730288371.214761065] [robot_state_publisher]: got segment FL_calf
[robot_state_publisher-1] [INFO] [1730288371.215025023] [robot_state_publisher]: got segment FL_calflower
[robot_state_publisher-1] [INFO] [1730288371.215050433] [robot_state_publisher]: got segment FL_calflower1
[robot_state_publisher-1] [INFO] [1730288371.215060802] [robot_state_publisher]: got segment FL_foot
[robot_state_publisher-1] [INFO] [1730288371.215069219] [robot_state_publisher]: got segment FL_hip
[robot_state_publisher-1] [INFO] [1730288371.215076931] [robot_state_publisher]: got segment FL_thigh
[robot_state_publisher-1] [INFO] [1730288371.215085316] [robot_state_publisher]: got segment FR_calf
[robot_state_publisher-1] [INFO] [1730288371.215093093] [robot_state_publisher]: got segment FR_calflower
[robot_state_publisher-1] [INFO] [1730288371.215101061] [robot_state_publisher]: got segment FR_calflower1
[robot_state_publisher-1] [INFO] [1730288371.215109062] [robot_state_publisher]: got segment FR_foot
[robot_state_publisher-1] [INFO] [1730288371.215117255] [robot_state_publisher]: got segment FR_hip
[robot_state_publisher-1] [INFO] [1730288371.215124904] [robot_state_publisher]: got segment FR_thigh
[robot_state_publisher-1] [INFO] [1730288371.215132712] [robot_state_publisher]: got segment Head_lower
[robot_state_publisher-1] [INFO] [1730288371.215140361] [robot_state_publisher]: got segment Head_upper
[robot_state_publisher-1] [INFO] [1730288371.215148361] [robot_state_publisher]: got segment RL_calf
[robot_state_publisher-1] [INFO] [1730288371.215156362] [robot_state_publisher]: got segment RL_calflower
[robot_state_publisher-1] [INFO] [1730288371.215164203] [robot_state_publisher]: got segment RL_calflower1
[robot_state_publisher-1] [INFO] [1730288371.215171883] [robot_state_publisher]: got segment RL_foot
[robot_state_publisher-1] [INFO] [1730288371.215179884] [robot_state_publisher]: got segment RL_hip
[robot_state_publisher-1] [INFO] [1730288371.215187693] [robot_state_publisher]: got segment RL_thigh
[robot_state_publisher-1] [INFO] [1730288371.215195341] [robot_state_publisher]: got segment RR_calf
[robot_state_publisher-1] [INFO] [1730288371.215203246] [robot_state_publisher]: got segment RR_calflower
[robot_state_publisher-1] [INFO] [1730288371.215211311] [robot_state_publisher]: got segment RR_calflower1
[robot_state_publisher-1] [INFO] [1730288371.215219216] [robot_state_publisher]: got segment RR_foot
[robot_state_publisher-1] [INFO] [1730288371.215226832] [robot_state_publisher]: got segment RR_hip
[robot_state_publisher-1] [INFO] [1730288371.215234417] [robot_state_publisher]: got segment RR_thigh
[robot_state_publisher-1] [INFO] [1730288371.215242674] [robot_state_publisher]: got segment base_footprint
[robot_state_publisher-1] [INFO] [1730288371.215250866] [robot_state_publisher]: got segment base_link
[robot_state_publisher-1] [INFO] [1730288371.215259027] [robot_state_publisher]: got segment front_camera
[robot_state_publisher-1] [INFO] [1730288371.215266932] [robot_state_publisher]: got segment imu
[robot_state_publisher-1] [INFO] [1730288371.215275412] [robot_state_publisher]: got segment map
[robot_state_publisher-1] [INFO] [1730288371.215283061] [robot_state_publisher]: got segment odom
[robot_state_publisher-1] [INFO] [1730288371.215290966] [robot_state_publisher]: got segment radar
[teleop_node-7] [INFO] [1730288371.184742546] [TeleopTwistJoy]: Linear axis x on 1 at scale 0.200000.
[teleop_node-7] [INFO] [1730288371.184899360] [TeleopTwistJoy]: Linear axis y on 3 at scale 0.200000.
[teleop_node-7] [INFO] [1730288371.184913665] [TeleopTwistJoy]: Angular axis yaw on 6 at scale 0.200000.
[twist_mux-8] [INFO] [1730288371.228989377] [twist_mux]: Topic handler 'topics.joy' subscribed to topic 'cmd_vel_joy': timeout = 0.500000s , priority = 10.
[twist_mux-8] [INFO] [1730288371.234469427] [twist_mux]: Topic handler 'topics.navigation' subscribed to topic 'cmd_vel': timeout = 0.500000s , priority = 5.
[async_slam_toolbox_node-10] [INFO] [1730288371.272586617] [slam_toolbox]: Node using stack size 40000000
[bt_navigator-15] [INFO] [1730288371.400424485] [bt_navigator]:
[bt_navigator-15]       bt_navigator lifecycle node launched.
[bt_navigator-15]       Waiting on external lifecycle transitions to activate
[bt_navigator-15]       See https://design.ros2.org/articles/node_lifecycle.html for more information.
[bt_navigator-15] [INFO] [1730288371.400721247] [bt_navigator]: Creating
[lifecycle_manager-18] [INFO] [1730288371.507645658] [lifecycle_manager_navigation]: Creating
[waypoint_follower-16] [INFO] [1730288371.513797125] [waypoint_follower]:
[waypoint_follower-16]  waypoint_follower lifecycle node launched.
[waypoint_follower-16]  Waiting on external lifecycle transitions to activate
[waypoint_follower-16]  See https://design.ros2.org/articles/node_lifecycle.html for more information.
[waypoint_follower-16] [INFO] [1730288371.514950183] [waypoint_follower]: Creating
[lifecycle_manager-18] [INFO] [1730288371.536271290] [lifecycle_manager_navigation]: Creating and initializing lifecycle service clients
[async_slam_toolbox_node-10] [INFO] [1730288371.625201117] [slam_toolbox]: Using solver plugin solver_plugins::CeresSolver
[async_slam_toolbox_node-10] [INFO] [1730288371.643255323] [slam_toolbox]: CeresSolver: Using SCHUR_JACOBI preconditioner.
[velocity_smoother-17] [INFO] [1730288371.680852789] [velocity_smoother]:
[velocity_smoother-17]  velocity_smoother lifecycle node launched.
[velocity_smoother-17]  Waiting on external lifecycle transitions to activate
[velocity_smoother-17]  See https://design.ros2.org/articles/node_lifecycle.html for more information.
[controller_server-11] [INFO] [1730288371.699994927] [controller_server]:
[controller_server-11]  controller_server lifecycle node launched.
[controller_server-11]  Waiting on external lifecycle transitions to activate
[controller_server-11]  See https://design.ros2.org/articles/node_lifecycle.html for more information.
[planner_server-13] [INFO] [1730288371.732355372] [planner_server]:
[planner_server-13]     planner_server lifecycle node launched.
[planner_server-13]     Waiting on external lifecycle transitions to activate
[planner_server-13]     See https://design.ros2.org/articles/node_lifecycle.html for more information.
[controller_server-11] [INFO] [1730288371.747956698] [controller_server]: Creating controller server
[planner_server-13] [INFO] [1730288371.753056171] [planner_server]: Creating
[foxglove_bridge-9] [INFO] [1730288371.771335324] [foxglove_bridge_component_manager]: Load Library: /opt/ros/humble/lib/libfoxglove_bridge_component.so
[foxglove_bridge-9] [INFO] [1730288371.850627948] [foxglove_bridge_component_manager]: Found class: rclcpp_components::NodeFactoryTemplate<foxglove_bridge::FoxgloveBridge>
[foxglove_bridge-9] [INFO] [1730288371.863529428] [foxglove_bridge_component_manager]: Instantiate class: rclcpp_components::NodeFactoryTemplate<foxglove_bridge::FoxgloveBridge>
[smoother_server-12] [INFO] [1730288371.889610396] [smoother_server]:
[smoother_server-12]    smoother_server lifecycle node launched.
[smoother_server-12]    Waiting on external lifecycle transitions to activate
[smoother_server-12]    See https://design.ros2.org/articles/node_lifecycle.html for more information.
[smoother_server-12] [INFO] [1730288371.894758097] [smoother_server]: Creating smoother server
[behavior_server-14] [INFO] [1730288371.947738630] [behavior_server]:
[behavior_server-14]    behavior_server lifecycle node launched.
[behavior_server-14]    Waiting on external lifecycle transitions to activate
[behavior_server-14]    See https://design.ros2.org/articles/node_lifecycle.html for more information.
[foxglove_bridge-9] [INFO] [1730288372.132669210] [foxglove_bridge]: Starting foxglove_bridge (humble, 0.8.0@) with WebSocket++/0.8.2
[pointcloud_to_laserscan_node-2] [INFO] [1730288372.211619514] [pointcloud_to_laserscan]: Got a subscriber to laserscan, starting pointcloud subscriber
[foxglove_bridge-9] [INFO] [1730288372.218498371] [foxglove_bridge]: [WS] Server running without TLS
[foxglove_bridge-9] [INFO] [1730288372.241328922] [foxglove_bridge]: [WS] WebSocket server listening at ws://0.0.0.0:8765
[foxglove_bridge-9] [INFO] [1730288372.253781438] [foxglove_bridge]: [WS] WebSocket server run loop started
[foxglove_bridge-9] [WARN] [1730288372.278594974] [foxglove_bridge]: Failed to add channel for topic "/query_result_node" (unitree_interfaces/msg/QtNode): package 'unitree_interfaces' not found, searching: [/home/unitree/ros2_ws/install/go2_robot_sdk, /home/unitree/ros2_ws/install/unitree_go, /home/unitree/ros2_ws/install/go2_interfaces, /home/unitree/ros2_ws/install/coco_detector, /opt/ros/humble]
[foxglove_bridge-9] [WARN] [1730288372.278850388] [foxglove_bridge]: Failed to add channel for topic "/qt_add_node" (unitree_interfaces/msg/QtNode): package 'unitree_interfaces' not found, searching: [/home/unitree/ros2_ws/install/go2_robot_sdk, /home/unitree/ros2_ws/install/unitree_go, /home/unitree/ros2_ws/install/go2_interfaces, /home/unitree/ros2_ws/install/coco_detector, /opt/ros/humble]
[foxglove_bridge-9] [WARN] [1730288372.279027139] [foxglove_bridge]: no .msg definition for unitree_go/msg/VoxelMapCompressed, falling back to IDL
[foxglove_bridge-9] [WARN] [1730288372.279185425] [foxglove_bridge]: Could not find definition for type unitree_go/msg/VoxelMapCompressed: unitree_go/msg/VoxelMapCompressed
[foxglove_bridge-9] [WARN] [1730288372.283666030] [foxglove_bridge]: no .msg definition for unitree_go/msg/ConfigChangeStatus, falling back to IDL
[foxglove_bridge-9] [WARN] [1730288372.283953959] [foxglove_bridge]: Could not find definition for type unitree_go/msg/ConfigChangeStatus: unitree_go/msg/ConfigChangeStatus
[foxglove_bridge-9] [WARN] [1730288372.284456273] [foxglove_bridge]: Failed to add channel for topic "/qt_add_edge" (unitree_interfaces/msg/QtEdge): package 'unitree_interfaces' not found, searching: [/home/unitree/ros2_ws/install/go2_robot_sdk, /home/unitree/ros2_ws/install/unitree_go, /home/unitree/ros2_ws/install/go2_interfaces, /home/unitree/ros2_ws/install/coco_detector, /opt/ros/humble]
[foxglove_bridge-9] [WARN] [1730288372.284645985] [foxglove_bridge]: Failed to add channel for topic "/arm_Command" (unitree_arm/msg/ArmString): package 'unitree_arm' not found, searching: [/home/unitree/ros2_ws/install/go2_robot_sdk, /home/unitree/ros2_ws/install/unitree_go, /home/unitree/ros2_ws/install/go2_interfaces, /home/unitree/ros2_ws/install/coco_detector, /opt/ros/humble]
[foxglove_bridge-9] [WARN] [1730288372.284777293] [foxglove_bridge]: Failed to add channel for topic "/api/vui/request" (unitree_api/msg/Request): package 'unitree_api' not found, searching: [/home/unitree/ros2_ws/install/go2_robot_sdk, /home/unitree/ros2_ws/install/unitree_go, /home/unitree/ros2_ws/install/go2_interfaces, /home/unitree/ros2_ws/install/coco_detector, /opt/ros/humble]
[foxglove_bridge-9] [WARN] [1730288372.284883222] [foxglove_bridge]: Failed to add channel for topic "/api/videohub/response" (unitree_api/msg/Response): package 'unitree_api' not found, searching: [/home/unitree/ros2_ws/install/go2_robot_sdk, /home/unitree/ros2_ws/install/unitree_go, /home/unitree/ros2_ws/install/go2_interfaces, /home/unitree/ros2_ws/install/coco_detector, /opt/ros/humble]
[foxglove_bridge-9] [WARN] [1730288372.285327868] [foxglove_bridge]: Failed to add channel for topic "/api/uwbswitch/response" (unitree_api/msg/Response): package 'unitree_api' not found, searching: [/home/unitree/ros2_ws/install/go2_robot_sdk, /home/unitree/ros2_ws/install/unitree_go, /home/unitree/ros2_ws/install/go2_interfaces, /home/unitree/ros2_ws/install/coco_detector, /opt/ros/humble]
[foxglove_bridge-9] [WARN] [1730288372.285479464] [foxglove_bridge]: Failed to add channel for topic "/qt_command" (unitree_interfaces/msg/QtCommand): package 'unitree_interfaces' not found, searching: [/home/unitree/ros2_ws/install/go2_robot_sdk, /home/unitree/ros2_ws/install/unitree_go, /home/unitree/ros2_ws/install/go2_interfaces, /home/unitree/ros2_ws/install/coco_detector, /opt/ros/humble]
[foxglove_bridge-9] [WARN] [1730288372.285880843] [foxglove_bridge]: Failed to add channel for topic "/api/sport_lease/response" (unitree_api/msg/Response): package 'unitree_api' not found, searching: [/home/unitree/ros2_ws/install/go2_robot_sdk, /home/unitree/ros2_ws/install/unitree_go, /home/unitree/ros2_ws/install/go2_interfaces, /home/unitree/ros2_ws/install/coco_detector, /opt/ros/humble]
[foxglove_bridge-9] [WARN] [1730288372.286033752] [foxglove_bridge]: Failed to add channel for topic "/api/sport_lease/request" (unitree_api/msg/Request): package 'unitree_api' not found, searching: [/home/unitree/ros2_ws/install/go2_robot_sdk, /home/unitree/ros2_ws/install/unitree_go, /home/unitree/ros2_ws/install/go2_interfaces, /home/unitree/ros2_ws/install/coco_detector, /opt/ros/humble]
[foxglove_bridge-9] [WARN] [1730288372.288785730] [foxglove_bridge]: Failed to add channel for topic "/api/sport/response" (unitree_api/msg/Response): package 'unitree_api' not found, searching: [/home/unitree/ros2_ws/install/go2_robot_sdk, /home/unitree/ros2_ws/install/unitree_go, /home/unitree/ros2_ws/install/go2_interfaces, /home/unitree/ros2_ws/install/coco_detector, /opt/ros/humble]
[foxglove_bridge-9] [WARN] [1730288372.289023670] [foxglove_bridge]: Failed to add channel for topic "/api/robot_state/response" (unitree_api/msg/Response): package 'unitree_api' not found, searching: [/home/unitree/ros2_ws/install/go2_robot_sdk, /home/unitree/ros2_ws/install/unitree_go, /home/unitree/ros2_ws/install/go2_interfaces, /home/unitree/ros2_ws/install/coco_detector, /opt/ros/humble]
[foxglove_bridge-9] [WARN] [1730288372.289172675] [foxglove_bridge]: Failed to add channel for topic "/api/sport/request" (unitree_api/msg/Request): package 'unitree_api' not found, searching: [/home/unitree/ros2_ws/install/go2_robot_sdk, /home/unitree/ros2_ws/install/unitree_go, /home/unitree/ros2_ws/install/go2_interfaces, /home/unitree/ros2_ws/install/coco_detector, /opt/ros/humble]

**Comment by kkjing0414** [comment]
There is another problem, if I open the map a day ago, my dog always can't find the correct position of his own, the new map is more accurate, I would like to ask if this has something to do with the time, the location of the objects in my field has not changed.

**Comment by kkjing0414** [comment]
Thank you very much for your help. Due to the time difference, I can't reply soon. Please forgive me.

**Comment by kkjing0414** [comment]
![70d9fac75c69036ff1b890b99142e753](https://github.com/user-attachments/assets/0f377d65-10db-484b-9a0f-2cb2b0daeea5)

**Comment by kkjing0414** [comment]
My dog has a drifting problem. Have you ever had one？

**Comment by abizovnuralem** [comment]
You should configure your nav2 params, I think some of the control issues (delays of the network and etc)

**Comment by abizovnuralem** [comment]
@kkjing4444 , If you have additional questions, please reopen the issue, thanks!
