### ISSUE TITLE
Errors loading geometries - URDF

### ISSUE THREAD

**Issue by MayooranT** [abizovnuralem/go2_ros2_sdk#27]
The Robot model is not visible because of this error for the URDF only. Seems like the .dae meshes are not loaded to display the model properly. At first that could be the path that causing errors but the path is correct. Are mesh files corrupted? 
![Screenshot from 2024-05-06 10-41-59](https://github.com/abizovnuralem/go2_ros2_sdk/assets/78531263/9ec21c05-fa06-4f91-baf3-86c4895d3c67)

**Comment by abizovnuralem** [comment]
Hi! What versions of ros and ubuntu are you using?

**Comment by MayooranT** [comment]
Ubuntu 20.04 and ROS Humble

**Comment by abizovnuralem** [comment]
Files are not corrupted, but it seems to me that for some reason your files could be corrupted on your local copy, can you try to redownload it one more time, please? I just checked it and on my local PC, I don't have this error. The second option is to change package:// to the real full path on your PC and check again (for debug purpose).
