### ISSUE TITLE
/point_cloud2 topic freezes when executing customized movements

### ISSUE THREAD

**Issue by kseniia99kh** [abizovnuralem/go2_ros2_sdk#43]
Hi, thank you for sharing the code! When i start ros2 launch go2_robot_sdk robot.launch.py, I can see the point cloud data for /robot0/point_cloud2, but if I execute the customized movement (using the physical controller, such as "sit down"), the said topic seems to freeze, and as soon as the robot returns into the standing position, it resumes the publishing...

before executing the customized movement:
![image](https://github.com/abizovnuralem/go2_ros2_sdk/assets/110399218/56fce69c-0d28-48c6-8150-e7878f534c49)
during "sitting down":
![image](https://github.com/abizovnuralem/go2_ros2_sdk/assets/110399218/10b9a0d2-29c7-45c2-9c2b-d7d43d8c475e)
and after returning to initial position:
![image](https://github.com/abizovnuralem/go2_ros2_sdk/assets/110399218/3fa160db-9236-4902-955c-735ffb1164ea)

Is there another way to position robot in a similar stance so it's possible to still generate the 3D map? Reason for this being a need to scan the whole room, including the ceiling

**Comment by abizovnuralem** [comment]
Hello, when the dog is in a sit-down position, the point cloud is not publishing any data, it is not freezing.  If you still want to get the point cloud while the dog is sitting, use cycloneDDS. In that case, the point cloud stream is working in any conditions.
