### ISSUE TITLE
Farthest point cloud in the opposite direction of movement disappears when moving go2

### ISSUE THREAD

**Issue by xutianzhuo** [abizovnuralem/go2_ros2_sdk#46]
Hi, thank you for sharing the code! 
When i start ros2 launch go2_robot_sdk robot.launch.py, I can see the point cloud data for point_cloud2, but the point cloud seems to have a range. When I move go2, the farthest point cloud in the opposite direction of movement disappears. It seems that the complete map cannot be saved. And I saw the same situation in the gif of Go2 Air/PRO/EDU lidar point cloud in your README. So, how can I save the complete point cloud map? Is there any setting that needs to be modified?

**Comment by abizovnuralem** [comment]
Hello, yes. You can save it via the params 
export MAP_SAVE=True
export MAP_NAME="3d_map"
After this you can use Meshlab to view it
