### ISSUE TITLE
stderr: ros2_go2_video No such file or directory while colcon build

### ISSUE THREAD

**Issue by artelrobotics** [abizovnuralem/go2_ros2_sdk#47]
I am using all instructions for installing and building package , but I am having issue with compiling ros2_go2_video package.
Please help!
![Screenshot from 2024-07-03 20-10-24](https://github.com/abizovnuralem/go2_ros2_sdk/assets/99396576/7450619d-589c-40a0-abeb-1901558c3f5d)

**Comment by abizovnuralem** [comment]
You forgot to use git clone --recurse-submodules https://github.com/abizovnuralem/go2_ros2_sdk.git

**Comment by artelrobotics** [comment]
I use it same as instruction
