### ISSUE TITLE
Having install issues on UB22.04 

### ISSUE THREAD

**Issue by rathken** [abizovnuralem/go2_ros2_sdk#49]
Hi, 
Can't seem to get this to build on UB22.04 
I have included a full install log that shows version of ros2 and rust 
Any help would be great, this is just the code / projects I have been looking for my GO2 EDU ...... 
[ros2_ws.log](https://github.com/user-attachments/files/16111600/ros2_ws.log)

**Comment by abizovnuralem** [comment]
You have a problem with sourcing the project. Check it please
