### ISSUE TITLE
Installing ROS2 in windows 11 pro

### ISSUE THREAD

**Issue by svarshneysjsu** [abizovnuralem/go2_ros2_sdk#51]
Hi There,

Is it possible to install ROS2 with windows 11 Pro?
I am reading the documentation and it is saying that Only Windows 10 is supported.
Also, in the readme file ROS2 humble version link is given but newer version is jazzy. 

will jazzy be supported or i should go with humble version?

Thanks in advance.

**Comment by abizovnuralem** [comment]
Hello, you can try to use docker inside windows 11

**Comment by hazemy** [comment]
Hello,

I would have to open this issue because it is not yet clear. Is support for Jazzy planned? @abizovnuralem 
@svarshneysjsu could you please share if you had any issue with Jazzy (if you already used it)?

Thanks!
