### ISSUE TITLE
Note on installing dependencies.

### ISSUE THREAD

**Issue by ValentinLeglise** [abizovnuralem/go2_ros2_sdk#71]
Hello,

I'm only creating this ticket to point out that in the first block of commands for installing :

mkdir -p ros2_ws
cd ros2_ws
git clone --recurse-submodules https://github.com/abizovnuralem/go2_ros2_sdk.git src
sudo apt install ros-$ROS_DISTRO-image-tools
sudo apt install ros-$ROS_DISTRO-vision-msgs
sudo apt install python3-pip clang
pip install -r requirements.txt
cd ..

from the ‘pip install -r requirements.txt’ command, I get an error because the shell is not located in the src folder in the ros2_ws directory.

It would be useful to add the command ‘cd src’ before the pip install to avoid this kind of problem.

I hope this helps.

**Comment by abizovnuralem** [comment]
Done with https://github.com/abizovnuralem/go2_ros2_sdk/pull/78 Thanks @ValentinLeglise !
