### ISSUE TITLE
[go2_driver_node-4] INFO:scripts.webrtc_driver:Connection state is closed

### ISSUE THREAD

**Issue by kkjing4444** [abizovnuralem/go2_ros2_sdk#88]
Hello dear author, I would like to ask what is the cause of [go2_driver_node-4] INFO:scripts.webrtc_driver:Connection state is closed? Hope to get your reply, thank you
![6fd2a14b721e22ab156e9fab2188fe0a](https://github.com/user-attachments/assets/e1fc061a-6670-4835-ab82-dccba047ed9d)

**Comment by tfoldi** [comment]
what is your robot's firmware version? can you share the full debug log of `go2_driver_node` ? you can run that independently with `ros2 run go2_robot_sdk go2_driver_node`

**Comment by kkjing0414** [comment]
> ros2 run go2_robot_sdk go2_driver_node

**Comment by kkjing0414** [comment]
<img width="705" alt="联想截图_20241007203221" src="https://github.com/user-attachments/assets/c61f805c-463b-4824-add2-0cb2f871d296">
 this log？

**Comment by kkjing0414** [comment]
I'm sorry, I don't know what to think about my version, I just re-installed it, there is a worse problem, at first it was the remote control dog walk, but the point cloud did not change, and there are these errors: [RVIZ2-5] [ERROR] [1728307688.446746262] [rviz2]: The link is static or has unrealistic inertia, so the equivalent inertia box will not be shown.
[rviz2-5]
[RVIZ2-5] [ERROR] [1728307688.447129319] [rviz2]: The link is static or has unrealistic inertia, so the equivalent inertia box will not be shown.
[rviz2-5]
[RVIZ2-5] [INFO] [1728307689.306326667] [rviz2]: Stereo is NOT SUPPORTED
[controller_server-11] [WARN] [1728307694.725134500] [local_Costmap. local_costmap]: Can't update static costmap layer, no map received
[planner_server-13] [WARN] [1728307696.176749087] [global_costmap.global_costmap]: Can't update static costmap layer, no map received.
Then came the launch, which could only load half the dog's body, which was even worse.
![Uploading 联想截图_20241007215441.png…]()

**Comment by kkjing0414** [comment]
I'm sorry, I don't know what to think about my version, I just re-installed it, there is a worse problem, at first it was the remote control dog walk, but the point cloud did not change, and there are these errors: [RVIZ2-5] [ERROR] [1728307688.446746262] [rviz2]: The link is static or has unrealistic inertia, so the equivalent inertia box will not be shown.
[rviz2-5]
[RVIZ2-5] [ERROR] [1728307688.447129319] [rviz2]: The link is static or has unrealistic inertia, so the equivalent inertia box will not be shown.
[rviz2-5]
[RVIZ2-5] [INFO] [1728307689.306326667] [rviz2]: Stereo is NOT SUPPORTED
[controller_server-11] [WARN] [1728307694.725134500] [local_Costmap. local_costmap]: Can't update static costmap layer, no map received
[planner_server-13] [WARN] [1728307696.176749087] [global_costmap.global_costmap]: Can't update static costmap layer, no map received.
Then came the launch, which could only load half the dog's body, which was even worse.
<img width="948" alt="联想截图_20241007215441" src="https://github.com/user-attachments/assets/5d25d261-2d7f-48e0-9cde-1fb8bf457620">

**Comment by abizovnuralem** [comment]
@kkjing0414  Hello, what connection method are you using?

**Comment by kkjing0414** [comment]
@abizovnuralem webrtc
