### ISSUE TITLE
I don´t think coco detection is working for me.

### ISSUE THREAD

**Issue by luiplapin1** [abizovnuralem/go2_ros2_sdk#91]
When I launch 
<code>source install/setup.bash
ros2 run coco_detector coco_detector_node
</code>

and on another terminal

<code>source install/setup.bash
ros2 topic echo /detected_objects</code>

I get nothing on the terminal. Do I have to pre-install any requirement or to active the GPU on the Go2?

**Comment by abizovnuralem** [comment]
Hello, do you see any error in logs?

**Comment by luiplapin1** [comment]
Not really, I get it blank

**Comment by abizovnuralem** [comment]
It would help if you ran a sdk first and then see if you have errors

**Comment by luispla22** [comment]
![image](https://github.com/user-attachments/assets/3d3ff49e-3657-4c01-aaff-0f5ce67484ea)
I get some error logs when I run the sdk.

**Comment by abizovnuralem** [comment]
Hello @luispla22 , have you sourced your code in the terminal?

**Comment by luispla22** [comment]
Yes! I've sourced the code, but still not working. I'm now using a "temporal fix" what is using yolo in the jetson, but I would like to have the integration with ROS2. 😪

**Comment by abizovnuralem** [comment]
@luispla22 , If you have additional questions, please reopen the issue, thanks!
